### ISSUE TITLE
访问没有权限的 Problem 页面会删除 Token

### ISSUE THREAD

**Issue by Gogomoe** [ArchOJ/feedback#6]
例如访问 https://oj.sustech.rocks/problem/56 后，会给出 Unauthorized 的提示
然后会发送一个 DELETE token 的请求退出登录，这个给个 redirect 就够了没必要 delete token 吧

**Comment by ziqin** [comment]
Sounds reasonable

**Comment by Gogomoe** [comment]
很合理吗…？我没见过任何一个系统鉴权失败会强制退出登陆的，就算你想让用户换个有权限的账号来，那也提示下就可以了吧

**Comment by ziqin** [comment]
您的建议很合理

**Comment by ziqin** [comment]
此问题从服务端进行修复。服务端应该仅在需要登录而用户却未登录时返回 401 Unauthorized。若当前用户权限不足，返回 403 Forbidden。

This problem is solved on server side. Servers shall respond a 401 Unauthorized only if authentication is require. For logged-in users without sufficient permission for an action, the server shall return a 403 Forbidden.
